name: changelog

on:
  release:
    types: [published]

jobs:
  generate-changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure git info
        run:  cd "${GITHUB_WORKSPACE}" && git config --global user.email "support@weave.works" && git config --global user.name "support"
      - name: genlog
        run: docker run --rm -v "${GITHUB_WORKSPACE}":"/usr/local/src/your-app" ferrarimarco/github-changelog-generator -u weaveworks -p weave-gitops
      - name: savelog
        env:
          CHANGELOG_SECRET: "${{ secrets.CHANGELOG_CREATION_TOKEN }}"
        run: GITHUB_ACCESS_TOKEN="${CHANGELOG_SECRET}" cd "${GITHUB_WORKSPACE}" && git checkout master && git add CHANGELOG.md && git commit -m'Add changelog' && git push

